
cards = [
    {'id':1,
    'sides':[-1,1,1,-1],
    'entrance': false,
    'name': 'Crypts'},
    {'id':2,
    'sides':[-1,1,1,1],
    'entrance': false,
    'name': 'Pool'},
    {'id':3,
    'sides':[-1,-1,1,1],
    'entrance': false,
    'name': 'Corridor'},
    {'id':4,
    'sides':[1,1,-1,-1],
    'entrance': false,
    'name': 'Vestry'},
    {'id':5,
    'sides':[1,-1,1,1],
    'entrance': false,
    'name': 'Chapel'},
    {'id':6,
    'sides':[1,-1,-1,-1],
    'entrance': false,
    'name': 'Great Tomb'},
    {'id':7,
    'sides':[-1,1,-1,-1],
    'entrance': false,
    'name': 'Store room'},
    {'id':8,
    'sides':[1,-1,-1,1],
    'entrance': true,
    'name': 'Entry Hall'}]