
cards = [
    {'id':1,
    'sides':[-1,1,1,-1],
    'entrance': false,
    'description': 'Small niches in the walls hold mummified remains.',
    'name': 'Crypts'},
    {'id':2,
    'sides':[-1,1,1,1],
    'entrance': false,
    'description': 'A pool holds water.',
    'name': 'Pool'},
    {'id':3,
    'sides':[-1,-1,1,1],
    'entrance': false,
    'description': 'The corridor is narrow, the ceiling supported by wooden beams.',
    'name': 'Corridor'},
    {'id':4,
    'sides':[1,1,-1,-1],
    'entrance': false,
    'description': 'Vaguely-humanoid wooden figures stand in a circle.',
    'name': 'Divination room'},
    {'id':5,
    'sides':[1,-1,1,1],
    'entrance': false,
    'description': 'An altar made of deer antlers and bones.', 
    'name': 'Altar'},
    {'id':6,
    'sides':[1,-1,-1,-1],
    'entrance': false,
    'description': 'A stone bier stands in the middle of the room.',
    'name': 'Great Tomb'},
    {'id':7,
    'sides':[-1,1,-1,-1],
    'entrance': false,
    'description': 'The ceiling is supported by pillars of hewn stone.',
    'name': 'Store room'},
    {'id':8,
    'sides':[1,-1,-1,1],
    'entrance': true,
    'description': 'Stairs lead down from the surface',
    'name': 'Entry Hall'}] 
