
cards = [
    {'id':1,
    'sides':[-1,1,1,-1],
    'entrance': false,
    'tags': ['burial'],
    'description': ['Small niches in the walls hold mummified remains.'],
    'name': 'Crypts'},
    {'id':2,
    'sides':[-1,1,1,1],
    'entrance': false,
    'tags': ['decoration'],
    'description': ['A pool holds water.'],
    'name': 'Pool'},
    {'id':3,
    'sides':[-1,-1,1,1],
    'entrance': false,
    'tags': ['decoration'],
    'description': ['The corridor is narrow, the ceiling supported by wooden beams.'],
    'name': 'Corridor'},
    {'id':4,
    'sides':[1,1,-1,-1],
    'entrance': false,
    'tags': [],
    'description': ['Vaguely-humanoid wooden figures stand in a circle.'],
    'name': 'Divination room'},
    {'id':5,
    'sides':[1,-1,1,1],
    'entrance': false,
    'tags': [],
    'description': ['An altar made of deer antlers and bones.'], 
    'name': 'Altar'},
    {'id':6,
    'sides':[1,-1,-1,-1],
    'entrance': false,
    'tags': ['treasure'],
    'description': ['A stone bier stands in the middle of the room.'],
    'name': 'Great Tomb'},
    {'id':7,
    'sides':[-1,1,-1,-1],
    'entrance': false,
    'tags': ['treasure'],
    'description': ['The ceiling is supported by pillars of hewn stone.'],
    'name': 'Store room'},
    {'id':8,
    'sides':[1,-1,-1,1],
    'entrance': true,
    'description': ['Stairs lead down from the surface.'],
    'tags': ['decoration'],
    'name': 'Entry Hall'},
    {'id':9,
    'sides':[-1,1,-1,1],
    'entrance': false,
    'description': ['The ceiling of this corridor has fallen in.'],
    'tags': ['impassible', 'rubble'],
    'name': 'Collapsed corridor'},
    {'id':10,
    'sides':[-1,1,1,-1],
    'entrance': false,
    'description': ['The ceiling of this corridor has fallen in.'],
    'tags': ['impassible', 'rubble'],
    'name': 'Collapsed corridor'},
    {'id':11,
    'sides':[-1,-1,1,-1],
    'entrance': true,
    'description': ['Stairs lead down from the surface.'],
    'tags': ['decoration'],
    'name': 'Entrance'},
    {'id':12,
    'sides':[1,-1,-1,-1],
    'entrance': false,
    'description': ['A large room with a vaulted ceiling.'],
    'tags': ['treasure'],
    'name': 'Store room'}
]
